# Generated by Django 5.1.6 on 2025-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('company_linkedin', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('lastcontacted', models.DateField()),
                ('project_description', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('document_upload', models.FileField(upload_to='static/file_uploads')),
            ],
        ),
    ]
