# Generated by Django 5.2 on 2025-04-30 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(null=True)),
                ('logs', models.CharField(max_length=100)),
                ('handle_by', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
