# Generated by Django 5.1.6 on 2025-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.BigIntegerField(max_length=100),
        ),
    ]
