# Generated by Django 5.2 on 2025-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_client_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_logs',
            name='status',
            field=models.IntegerField(choices=[(1, 'Proposal Sent'), (2, 'Contacted'), (3, 'On Hold'), (4, 'Negotiation'), (5, 'Lost'), (6, 'Rejected')], default=4),
        ),
    ]
