# Generated by Django 5.1.6 on 2025-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_client_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
