# Generated by Django 5.2 on 2025-05-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_client_logs_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('assigned_to', models.IntegerField(null=True)),
                ('assigned_by', models.IntegerField()),
                ('task_status', models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Done')], default=1)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
