# Generated by Django 5.2 on 2025-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_client_priority_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
