# Generated by Django 5.2 on 2025-04-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_user_is_admin_user_is_super_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super_admin',
        ),
    ]
