# Generated by Django 5.2 on 2025-05-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_usernotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotes',
            old_name='user_id',
            new_name='user',
        ),
    ]
