# Generated by Django 5.2 on 2025-04-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_user_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
