# Generated by Django 5.2 on 2025-05-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_user_id_usernotes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotes',
            old_name='client_id',
            new_name='client',
        ),
    ]
